(179839148) Add 'latest' tags to support ECR lifecycle
greenriver/ecs-deploy-public pull request #1
Opened 2021-10-15 16:58 UTC by andyzito

This adds tags for the web, base, and dj images: `latest-{env:production|staging|sandbox}--{variant:web|base|dj}`. The `env` is based on branch name, meaning that this won't apply `latest-` tags to images on branches other than prod/staging/sandbox.

This is tested and implemented in HNMI: https://github.com/greenriver/hnmi/pull/1128

2021-10-18 15:37 UTC, yakloinsteak requested changes

2021-10-18 15:37 UTC, yakloinsteak commented on .github/workflows/ecs.yml
> +        if [[ "$BRANCH" =~ ^(production|staging|sandbox)$ ]]; then
even though this repo is only in use by one client, I'm thinking we might want to match more generically on something like `/^deploy-/` and pull out the string after the dash as the token to add after latest below. What do you think?

2021-10-18 16:54 UTC, andyzito commented on .github/workflows/ecs.yml
> +        if [[ "$BRANCH" =~ ^(production|staging|sandbox)$ ]]; then
I think that's a great idea. Probably safe to keep those three hardcoded branch names as well, if they're very commonly used deploy branches, but I'm open to dissenting opinions.

2021-10-18 17:15 UTC, yakloinsteak commented on .github/workflows/ecs.yml
> +        if [[ "$BRANCH" =~ ^(production|staging|sandbox)$ ]]; then
I like your idea. I've seen "sandbox" in two different repos that I can think of, and it almost certainly would mean something similar in other projects. "demo" is another commonish one. Perhaps "main" as well.

2021-10-20 14:22 UTC, andyzito commented
@yakloinsteak Added the extra branches you mentioned, as well as matching on deploy-*.

2021-10-20 14:29 UTC, yakloinsteak approved these changes
Merge away if you're ready, and thanks!

2021-10-20 14:34 UTC, merged